### ISSUE TITLE
Users ->custom_data -> realtime

### ISSUE THREAD

**Issue by ciaoamigo** [pusher/chatkit-client-js#100]
I need that when a user changes and/or sets a custom data (custom_data), it is propagated in real time to all connected users.
How can I do?

**Comment by hamchapman** [comment]
It's not something that we currently support, but we do have plans to in the future. If you need to synchronise something like that right now then you could use Channels (https://pusher.com/channels) to send the realtime updates when a change occurs.

**Comment by ciaoamigo** [comment]
I need this in the chatrooms linked to the user.
Example if a user turns on / off the camera, etc.
Know the times, when will it be ready?

**Comment by hamchapman** [comment]
I'm afraid I can't give you a specific timeframe for when this will be available. It's something that's been specced out by our team so we know the work involved but we haven't gotten to it just yet.

**Comment by callum-oakley** [comment]
Closing this because it's a feature request for the product as a whole not just for this SDK. Please [contact support](mailto:support@pusher.com) if this feature is important for your use case.
