### ISSUE TITLE
cannot read property default of undefined

### ISSUE THREAD

**Issue by kingtross88** [pusher/chatkit-client-js#101]
How do i create a chat kit user in my app. I'd like to take the authentication UID to pusher

const chatkit = new Chatkit.default({
        instanceLocator: "instance",
        key: "myKey"
      })

      chatkit.createUser({
        id: "23923hs123",
        name: "James Bond"
      })

I'm using the same code from the site.

**Comment by gianpaj** [comment]
See this https://github.com/pusher/chatkit-client-js/issues/87 - How do you create users?

basicall you need to do it from your backend server, not from the client

**Comment by gileswells** [comment]
@kingtross88 did you get this working?

**Comment by mdpye** [comment]
Going to close this one as advice has been offered and it's now stale.
