### ISSUE TITLE
roomId string or number?

### ISSUE THREAD

**Issue by dsgrillo** [pusher/chatkit-client-js#103]
Hi!

I've started having problems today due a mismatch in the type of `roomId`.

As far as I see, in most places the expected type is to be number, but the `roomId` returned by the `newMessage` hook is string. 

Is there an expected date to release #102 ?

Is it safe to parse it locally to integer and just ignore the upcoming change?

Thanks!

**Comment by callum-oakley** [comment]
Hi there,

Currently room IDs should always be numbers. In the next breaking version change we're switching to string room IDs everywhere with the ultimate goal of allowing user provided room IDs. You shouldn't be seeing string room IDs anywhere just yet though... what version of the SDK are you using, and where specifically are you seeing string roomIDs? (in the `message` object passed to the `newMessage` hook?)

**Comment by dsgrillo** [comment]
Hi @callum-oakley, thanks for the prompt reply!

I'm using the version `0.7.17`

When I opened this issue the problem was occurring in the `onNewMessage` hook

```
user.subscribeToRoom({
    roomId: room.id,
    hooks: {onNewMessage: (message) => dispatch(onNewMessage(message))},`
}) 
```

And I've fixed with  `message.roomId = parseInt(message.roomId)`.

I've just tried to remove the parsing and it seems to be working properly. I've also checked the Websocket frame (in the chrome network tab), and now the value seems indeed to be coming as number (but I didn't check back then.)

I guess I didn't collected much data when the error occurred, I supposed the chatkit server was returning the `roomId` in this specific hook as string.

In any case, I'll keep an eye to see if it happens again and let you know.

Thanks!

**Comment by callum-oakley** [comment]
Thanks for bringing this to our attention! Turns out it was a bug we'd introduced as part of the aforementioned work towards having room IDs be strings in the future. You shouldn't see this happen again but if you do please do let us know. Cheers :)

**Comment by shahisa** [comment]
Hey @callum-oakley  I'm having a similar issue I thought the bug was fixed ? :/ . My code is as follows:
```
currentUser.subscribeToRoom({
        roomId: 19395163,
        hooks:{
          onNewMessage: message => {
            console.log('message.text: ', message.text)
          }
```
I thought roomId is an integer however I get the error its expecting a string. 

<img width="1051" alt="screen shot 2019-01-20 at 18 55 11" src="https://user-images.githubusercontent.com/12785744/51446801-f9c3f100-1ce4-11e9-8c08-cb702e2bc20b.png">

**Comment by Pawan72** [comment]
how to get individual message from a room through roomID?I am trying "message.text" but i am getting the message as undefined
