### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://us1.pusherplatform.io/ws.

### ISSUE THREAD

**Issue by neuropass** [pusher/chatkit-client-js#105]
The last 3 days the app has been plagues on/off with this error:

`Firefox can’t establish a connection to the server at wss://us1.pusherplatform.io/ws.`

Then of course the old error follows as well:
`Logger.ERROR:  error establishing user subscription: chunk-vendors-bbchat-vendors.js:31:47095
Logger.ERROR:  Error: "user subscription timed out"`

Any ideas on what's happening guys?

**Comment by callum-oakley** [comment]
Are you still seeing this? If you could note the exact time if it happens again so we can take a look at things our end that would be great. It would be good to get a look at the network tab of the dev tools as well if possible.

**Comment by callum-oakley** [comment]
Just to let you know we've been able to catch this happening now, so we'll certainly be looking in to it. Thanks for reporting.

**Comment by neuropass** [comment]
fantastic! Thanks again! I'll report if it happens again and ill check the network tabs etc.

**Comment by neuropass** [comment]
I think its ok to close this one. I haven't see this on my end anymore. Thanks again for looking into this!

**Comment by callum-oakley** [comment]
Good to hear, let us know if it pops up again :)
