### ISSUE TITLE
Chatkit throws 'Field `id` is required.' error.

### ISSUE THREAD

**Issue by heyypatrick** [pusher/chatkit-client-js#106]
I've been working on a chat system but now it throws an error "Field 'id' is required." It was working yesterday but upon checking now I encountered this error.

Here's my code.

    const tokenProvider = new Chatkit.TokenProvider({
            url: "https://us1.pusherplatform.io/services/chatkit_token_provider/v1/ea217a79-e941-4537-bfcf- 
       b6cc1ab148f8/token"
        });

        const chatManager = new Chatkit.ChatManager({
            instanceLocator: "v1:us1:ea217a79-e941-4537-bfcf-b6cc1ab148f8",
            userId: 'Front-desk',
            tokenProvider: tokenProvider
        });

        var fd_chat_room_id =  Number($('input[name=chat_room_id]').val());

        chatManager
            .connect()
            .then(currentUser => {
                currentUser.joinRoom({
                    roomId: fd_chat_room_id
                }).then(room => {
                    console.log(room);
                });
            });

![hp_chat](https://user-images.githubusercontent.com/7449006/47765816-c46fbe80-dd06-11e8-94f1-09f02dc4be9f.png)

**Comment by vivangkumar** [comment]
Hi! What version of the client are you using?

**Comment by heyypatrick** [comment]
Hi! I'm currently using the latest version 1.0.2.

**Comment by vivangkumar** [comment]
@heyypatrick interesting. Could you please share a screenshot of the network tab as well please?

**Comment by heyypatrick** [comment]
I'm having an error at /users_by_ids end-point.
![chatkit_error](https://user-images.githubusercontent.com/7449006/47780782-087ab780-dd37-11e8-9c51-1103ae0138a4.png)

**Comment by vivangkumar** [comment]
Yeah, I think we've figured out what the issue is. Seems to be an issue with the way we published packages. We're fixing it as we speak. Hang in there! Apologies for the inconvenience.

**Comment by heyypatrick** [comment]
Thanks @vivangkumar !

**Comment by vivangkumar** [comment]
@heyypatrick are you sure you're running `1.0.2`? How are you pulling in the dependency?

**Comment by callum-oakley** [comment]
Just a hunch in the meantime:

You've installed `@pusher/chatkit-client` and have version `1.0.2`, but you also still have `@pusher/chatkit` and are importing/requiring that (which will be `0.8`). If you import require `@pusher/chatkit-client` instead you'll be good (if I'm write, otherwise we'll keep investigating 😛).

**Comment by heyypatrick** [comment]
I'm pulling the dependency by using

**Comment by heyypatrick** [comment]
I'm pulling the dependency by using: 
`<script src="https://unpkg.com/@pusher/chatkit"></script> `

It is now in version 0.7.18 for the script @vivangkumar

**Comment by heyypatrick** [comment]
I'm importing it using the script tag @callum-oakley

**Comment by callum-oakley** [comment]
@heyypatrick we had to pull the 1.0 release from `@pusher/chatkit` because of people using the script tag without versioning it (which we erroneously did in our docs, so our fault!). The 1.0 release, and all future releases, is now at `@pusher/chatkit-client`. If you use

```html
<script src="https://unpkg.com/@pusher/chatkit-client@1.0.2"></script>
```

then you'll get the latest version. Sorry about the confusion!

**Comment by heyypatrick** [comment]
Ohh I see. I understand. Thanks @callum-oakley and @vivangkumar :+1:

**Comment by vivangkumar** [comment]
Great! Thanks @heyypatrick and sorry for the confusion!

**Comment by heyypatrick** [comment]
Hi @vivangkumar i'm using the version 1.01 of the chatkit client. Is it available? Seems like not working for me anymore. I imported it using:
    `<script src="https://unpkg.com/@pusher/chatkit@1.0.1/dist/web/chatkit.js"></script>`

**Comment by vivangkumar** [comment]
@heyypatrick We pulled that release and have a new version `1.0.2` released under `chatkit-client`.
`<script src="https://unpkg.com/@pusher/chatkit-client@1.0.2/dist/web/chatkit.js"></script>`

**Comment by heyypatrick** [comment]
Ohh I see. Thank you @vivangkumar , again. :smiley:

**Comment by vivangkumar** [comment]
No worries :)
