### ISSUE TITLE
User presence is always offline

### ISSUE THREAD

**Issue by tahmidsadik112** [pusher/chatkit-client-js#107]
Both room level and connection level `onPresenceChanged` hook is always giving the current state of user as offline. Even when the user is sending messages.
I am using chatkit-client 1.0.0

**Comment by callum-oakley** [comment]
Hi @tahmidsadik112,

I'm not immediately able to reproduce this, how are you testing it? And are all of the clients you're testing with on 1.x? Due to the changes to the backend between 0.x and 1.x, 0.x clients will see 1.x as offline and vice versa.

**Comment by tahmidsadik112** [comment]
@callum-oakley My bad, I only upgraded one client. I will upgrade the other clients and let you know.

**Comment by callum-oakley** [comment]
Great, thanks :)

**Comment by tahmidsadik112** [comment]
Upgrading all the clients to 1.0.2 fixed the issue. Closing.

**Comment by achang97** [comment]
I am getting the same issues with version 1.2.0 - the presence is always offline.
