### ISSUE TITLE
Not exists react-native.js

### ISSUE THREAD

**Issue by killermu94** [pusher/chatkit-client-js#113]
In the root folder not existe the file called "react-native.js"
src: node_modules/@pusher/chatkit-client

My package version is 1.0.4

**Comment by callum-oakley** [comment]
Good catch, we recently moved to a whitelist instead of a blacklist for our npm ignore. This one slipped through the net! Will have a fix pushed asap.

**Comment by callum-oakley** [comment]
@killermu94 I just released 1.0.5 which should fix this. Thanks for bringing it to our attention.
