### ISSUE TITLE
Chatkit throws 'service_unavailable_error' error at chatkit-client 1.0.2

### ISSUE THREAD

**Issue by heyypatrick** [pusher/chatkit-client-js#115]
I have been using Chatkit at development for weeks now but it seems that it's not working again for me. I imported the script using:
`<script src="https://unpkg.com/@pusher/chatkit-client@1.0.2/dist/web/chatkit.js"></script>`
Everything was working fine yesterday but upon checking today it's now throwing an exception. Any clues how did this happened? Thanks!

Console:
![ckit_error2](https://user-images.githubusercontent.com/7449006/48283847-afc6bf80-e498-11e8-9e74-5dd4f6044a28.png)

Network tab:
![ckiiiitt](https://user-images.githubusercontent.com/7449006/48284700-18af3700-e49b-11e8-8703-41c70765384c.png)

**Comment by kkcodes** [comment]
Looks like something wrong at their end, its not working till now. Also, it's out of beta maybe they are working on it. Hope, it will be fixed soon.

**Comment by heyypatrick** [comment]
Looks like a major update will be out soon. Anyway, thanks @kkcodes !

**Comment by heyypatrick** [comment]
It's all working fine now!
