### ISSUE TITLE
onPresenceChanged won't trigger

### ISSUE THREAD

**Issue by senky** [pusher/chatkit-client-js#117]
Hello,
I don't understand this weird situation but here it is. I have two Chatkit instances initiated in one page (one is for main chat, another for 1-1 messages but that is irrelevant). I have `onPresenceChanged` set on both `chatManager.connect`s:

```
chatManager.connect({
	onPresenceChanged: (state, user) => {
		console.log(state, user);
	},
	...
})
```

But the main one triggers console.log nicely, while 1-1 one won't trigger anything. I even tried to remove `onPresenceChanged` from the main chat but it won't helped anything. I just don't receive any `onPresenceChanged` events whatsoever.

**Comment by mdpye** [comment]
Are the two instances connected using the same user id?
Are they connected to the same chatkit instance locator?

**Comment by senky** [comment]
Yes, they use the same user id and the same instance locator. But as I said, even when I remove the listener from the main chat (which works), the other one still won't trigger.

**Comment by mdpye** [comment]
I'm not sure this is a supported way of using it - there are no globals in the library, so two clients with different instances or different user IDs should work just fine, but the browser may do strange things when it notices that some requests are identical to others.

Leave it with us, but I have to ask - why two instances? If they're for the same user and instance, they should be getting all the same data and triggering all the same callbacks. Only the set of subscribed rooms will be different, but you can provide hooks per room subscription, so you could direct those callbacks to the correct (one to one or global) listeners...

**Comment by senky** [comment]
But everything else works just fine, this one listener is problematic.

Why two instances? One is for 1-1 messaging and another one for public rooms users can chat together. 1-1 chat is used on every page of the site but public rooms are available only on one dedicated page. So it is obviously not good to load all JS dedicated to public rooms chat on every page just because it's coupled with the 1-1 chat. So I decoupled it and deliver 1-1 chat everywhere and public rooms only on one page. Nevermind, it didn't cause any problem to-date. I will investigate further, but for now the only info I can give you is that `onPresenceChanged` listener isn't fired when it should be.

**Comment by vivangkumar** [comment]
Hi @senky!

I tried reproducing this on my end, with no luck. Could you post a snippet of some minimal code that reproduces this? The way I went about doing this is like so:

```js
const tokenProvider = new Chatkit.TokenProvider({
  		  url: "<TOKEN PROVIDER URL>"
		  });

  		const chatManager1 = new Chatkit.ChatManager({
  		  instanceLocator: "<INSTANCE LOCATOR>",
  		  userId: "testuser",
  		  tokenProvider: tokenProvider
  		});

      chatManager1.connect({
        onPresenceChanged: (state, user) => {
          console.log(state, user);
        },
      }).then(currentUser => {
        currentUser.subscribeToRoom({
          roomId: currentUser.rooms[0].id,
          hooks: {
            onMessage: message => {
              console.log(message)
            }
          }
        })
        console.log("Connected as user ", currentUser);
      }).catch(error => {
        console.error("error:", error);
      });

      const chatManager2 = new Chatkit.ChatManager({
        instanceLocator: "INSTANCE LOCATOR",
        userId: "testuser",
        tokenProvider: tokenProvider
      });

      chatManager2.connect({
        onPresenceChanged: (state, user) => {
          console.log(state, user);
        },
      }).then(currentUser => {
        currentUser.subscribeToRoom({
          roomId: currentUser.rooms[0].id,
          hooks: {
            onMessage: message => {
              console.log(message)
            }
          }
        })
        console.log("Connected as user ", currentUser);
      }).catch(error => {
        console.error("error:", error);
      });
```

On another page, I had similar code running, but with one instance and connected to a different user. The users were in the same room. On refreshing the page of the other user, both connections received the presence event. I inspected the Websocket frames too, and confirmed that both connections received the same presence events.

Am I missing something else here?

**Comment by vivangkumar** [comment]
@senky Don't know if you've looked at the reply above - is there something I'm missing? Are you still experiencing the same behaviour?

**Comment by senky** [comment]
Okay so the newest status is that it basically started to work out of itself. Sometimes it misses an event, but it works. Maybe it was a temporary server issue?

**Comment by vivangkumar** [comment]
Could certainly be. There were also a few issues with the JS library and web sockets after reconnections, which we've fixed on our end. It could've contributed to it. However, I tried to reproduce this for a while and had no success. I'm going to close the issue for now, but if you do notice again, could you reopen this issue?
