### ISSUE TITLE
503 - service_unavailable

### ISSUE THREAD

**Issue by Drengel1990** [pusher/chatkit-client-js#118]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/18291994/48446739-b27c2a00-e7a2-11e8-9fe8-801cfceb1c41.png">

**Comment by heyypatrick** [comment]
I'm also having this error for the past few days. But I think it's an error with their end. Hope it will be fixed soon. Though there are some hours that it's working fine and sometimes they're not. Thus, its fluctuating. :smile:

**Comment by Drengel1990** [comment]
16:37 - europe/kiev timezone
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18291994/48489410-a9836b00-e82b-11e8-8be8-1faa7c21a5d2.png">

**Comment by Drengel1990** [comment]
1542206579
<img width="589" alt="image" src="https://user-images.githubusercontent.com/18291994/48489806-8ad1a400-e82c-11e8-8a76-7ecc5c5ebcaa.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/18291994/48489825-94f3a280-e82c-11e8-8c7c-a74efc8c0bbf.png">

**Comment by Drengel1990** [comment]
@callum-oakley ^^

**Comment by callum-oakley** [comment]
thanks @Drengel1990

trying to resolve asap 🤞

**Comment by callum-oakley** [comment]
We've just deployed what we hope is a fix for this, please let us know if you see it happening again.

**Comment by hamchapman** [comment]
Closing as this issue is fixed. Please open a new issue if the problem reoccurs 👍
