### ISSUE TITLE
currentUser.users doesn't contain all users

### ISSUE THREAD

**Issue by senky** [pusher/chatkit-client-js#119]
I'm not sure how is this supposed to work, but `currentUser.users` doesn't contain all users of the instance. It doesn't even include all users who share rooms with current user. As far as I investigated, it only contains a list of users who sent message to current user (that means to rooms where current user is member).

I believe this is not intended, is it? I use `userStore` to generate presence indicators because it's much more convenient than listening to `onPresenceChange`, but obviously many users are displayed as offline even though they are online because `currentUser.users` doesn't contain such users.

**Comment by achang97** [comment]
I have the same issue with individual rooms - the getter for users doesn't return a consistent result.

**Comment by callum-oakley** [comment]
@senky `currentUser.users` should contain all the users in all the rooms that you are *subscribed* to. Does this explain what you're seeing or is there something else going on?

@achang97 under which circumstances are you seeing this? Do you have a reproduction?

**Comment by senky** [comment]
@callum-oakley as subscribed, that's the key. Ok thanks.

PS: Is there a way to know the presence status of user outside of subscribed rooms?

**Comment by hamzadhia** [comment]
I have the same issu, but when i call currentUser.rooms, and i fetch the object, i see all the data with console.log, but its return an empty array when i try to get userIds proprety.
below my code
`let romms = currentUser.rooms;
for (var romm in romms) {
console.log(romm.userIds); // here the empty array
console.log(romm); // here i can see all data as i want
}`
Any idea please??

**Comment by hamchapman** [comment]
`room.userIds` should be populated when you have subscribed to the room. I imagine that's what you need to do to see them appear

**Comment by hamchapman** [comment]
The `subscribeToRoom` call returns a promise that you can call `.then(room => { ... })` on

**Comment by MarkMurphy** [comment]
This still seems to be an ongoing issue.

**Comment by senky** [comment]
It is. Right now I am in a situation when every user can chat with everyone else in 1-1 chat. So imagine you have 1000 users. Every user can chat with 999 users. I obviously list them all in the left sidebar. I want to give everyone an online/offline indicator. What I need right now is to subscribe to 999 rooms just to receive a user status. That doesn't seem like optimal solution...

**Comment by neuropass** [comment]
any progress about this situation @hamchapman @callum-oakley are you guys implementing anything or this is a no go situation?

**Comment by djvistasa** [comment]
> It is. Right now I am in a situation when every user can chat with everyone else in 1-1 chat. So imagine you have 1000 users. Every user can chat with 999 users. I obviously list them all in the left sidebar. I want to give everyone an online/offline indicator. What I need right now is to subscribe to 999 rooms just to receive a user status. That doesn't seem like optimal solution...

I am facing this exact issue, I have 5000 plus users and would like to know their statuses. Subscribing to 5000 rooms just to get their statuses doesn't seem right. Updating manually on the status `onPresenceChanged: (state, user) => {
  console.log(`User ${user.name} is ${state.current}`)
}` doesnt seem right either as I would have to filter all 5000 of my users to find the one in question and modify the object each time someone comes online, doesn't seem right

**Comment by callum-oakley** [comment]
We've added this as a feature request to the backlog since it certainly needs some thought on how this would work in a scalable way. In the meantime please [contact support](support@pusher.com) if this is something that is important to your use case.

**Comment by tabrza** [comment]
@callum-oakley - I'm trying to build out a live chat customer support portal. I need to ensure the user cannot send a message if the support agent is offline. I have subscribed to the room on each occasion (when user starts chat). In the object when checking on currentRoom.users and checking the presence, i am able to see the online status of the user and agent. however, when trying to access it in the code it is non-enumerable and gives me a status of undefined (for the agent from the customer side). please advise if this ties into the above or if you have a suggested solution for this?

**Comment by callum-oakley** [comment]
This doesn't tie in to the above no, the presence state should be defined on `room.users`. Can we see the code you're trying to use to access the presence status? Either in a new issue or in an email to [support@pusher.com](mailto:support@pusher.com).

**Comment by tabrza** [comment]
> This doesn't tie in to the above no, the presence state should be defined on `room.users`. Can we see the code you're trying to use to access the presence status? Either in a new issue or in an email to [support@pusher.com](mailto:support@pusher.com).

Sure, let me just create a new issue. Thanks!
