### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by RichieMcMullen** [pusher/chatkit-client-js#120]
![screenshot 2018-11-22 at 18 54 29](https://user-images.githubusercontent.com/8255180/48918992-10d29800-ee88-11e8-80c8-9110bb218093.png)

I'm getting a bunch of errors, notably a `cors` error when trying to access the api.

**Comment by callum-oakley** [comment]
Hi! It looks like the CORS errors are from your token provider. You'll be able to confirm or deny this if you check the request in the network tab.

**Comment by hamchapman** [comment]
Closing as it does appear to be related to your token provider endpoint. Let us know if you find otherwise.
