### ISSUE TITLE
Can't Access files that are older than a few days

### ISSUE THREAD

**Issue by vishesh774** [pusher/chatkit-client-js#124]
Hi,

I am trying to send some files and then open them in my application. The file is sent perfectly and i can also open the same immediately.

The actual error happens after a few days. I try to access the file, it says "Specified Key does not 
exist".

Below is the log of the response from the s3 bucket:

```
<Error>
 <Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>19487149/charges.pdf</Key>
<RequestId>CD2415BBABC46915</RequestId>
<HostId>
ZAzcUXllO6vWeueDHK1N6w0ksJgBDmGn9ZXA9hue8mVJIsOsPaLtfO/tygQ6obCfLIgvJvS/1U4=
</HostId>
</Error>
```

Can anyone help me on this please?

**Comment by hamchapman** [comment]
@vishesh774 please could you send us the attachment URL that you're trying to fetch that isn't working? Feel free to email me at hamilton@pusher.com with more information if that's easier for you

**Comment by vishesh774** [comment]
Hey @hamchapman ,

Thanks for the response. I see that there is a difference in the attachment URL that is returned to us based on how old they are. For eg, anything that is valid has a correct url and older attachment which i cant fetch is in the following format:

https://chatkit-file-service-us1.s3.amazonaws.com/19487149/charges.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<Crendential>&X-Amz-Date=20181213T120915Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=<Signature>

If you notice this clearly, this has missed out the <instanceId> value from the url. Thus unable to locate the file.

I though tried a different approach to generate a token and then hit the <files> API to GET with a valid token. It seemed to work fine though. But in case when i am trying to show images directly, this creates a bit of a problem.

**Comment by s5963028** [comment]
Hi, 
I am facing the same problem.

I am using Chatkit on my react native app.

I need to display uploaded images attachments in my chat component.
 I use the url() function to resolve the URL of the attachment, but when I try to access the file, I get that XML error: "The specified key does not exist"

**Comment by s5963028** [comment]
anyone?

**Comment by callum-oakley** [comment]
@s5963028 sorry for the delay in picking this up, it will be easier to get to the bottom of what's going on if we can dig in with your instance details. Can you email support@pusher.com please?

**Comment by callum-oakley** [comment]
I believe this issue was fixed long ago. Please re-open if I'm mistaken.
