### ISSUE TITLE
Room.users array empty even after subscription

### ISSUE THREAD

**Issue by boboci9** [pusher/chatkit-client-js#126]
Hi,

I have an issue with the room.users array being empty even after I have subscribed to the room. I put a console log a couple f minutes timeout and then I have the userIds, but I need a callback or some way to know if a subscription to a room is finished. Is there such thing in your API?

Thanks for the awesome work, a great package!!!

**Comment by yarsunny** [comment]
Hi Have the same issue as @boboci9 

Attaching the code below.

`const tokenProvider = new Chatkit.TokenProvider({
      url: `${environment.api_url}/chatkit/auth`
    });

    const chatManager = new Chatkit.ChatManager({
      instanceLocator: '<instance locator>',
      userId: uid,
      tokenProvider
    });

    chatManager.connect().then(currentUser => {
      // subscribe to the rooms to receive messages.
      currentUser.rooms.forEach(room => {
        currentUser.subscribeToRoom({
          roomId: room.id,
          messageLimit: 20,
          hooks: {
            onAddedToRoom: room => {
              console.log(`Added to room ${room.name}`);
            },
            onMessage: this.onReceiveMessage,
            onPresenceChanged: this.onChangePresence,
            onNewReadCursor: this.onChangeReadCursor
          }
        });
      });

      this.currentUser = currentUser;
      this.users = this.currentUser.users;

      // the below line gives me empty array.
      console.log(currentUser.users)

      // this gives me proper users
      setTimeout(() => {        
        console.log(currentUser.users)
      }, 3000)
      
    });`

**Comment by hamchapman** [comment]
As noted in #119:

> The `subscribeToRoom` call returns a promise that you can call `.then(room => { ... })` on

**Comment by MarkMurphy** [comment]
> As noted in #119:
> 
> > The `subscribeToRoom` call returns a promise that you can call `.then(room => { ... })` on

Already doing this, the problem still seems to occur.

**Comment by callum-oakley** [comment]
Closing this as stale. Please [contact support](mailto:support@pusher.com) if this is still an issue on the latest version.
