### ISSUE TITLE
Message createdAt isn't honored when sending messages

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-client-js#128]
I'm trying to use Chatkit while the user is offline. The main idea is to automatically connect the user and send the messages sent while they were offline. 

For this, I'm specifying the `createdAt` property of the message when sending it:

```
let msg = {
      text: "Hello!",
      createdAt: message.createdAt, // specifying it here works, but its not being honored
      roomId: 123
 };

this.currentUser.sendMessage(msg);
```

`message.createdAt` is a date object which contains the time in which the message was actually sent while the user is still offline. But it seems like this property isn't actually being used when the message is sent. Instead, it uses the time in which the message actually gets sent when the user goes back online.

**Comment by hamchapman** [comment]
@anchetaWern what's the use case for seeing the `createdAt` to a date when the user was offline? 

What's the behaviour you'd expect if you set that to a time that the user was offline and then in the time between then and when the user reconnected there had been lots of other messages sent by other users? Should the message be inserted "in the past" or would you want the message to appear as though it was sent as soon as the user came back online, but have some sort of metadata saying that it was originally written at the `createdAt` date?

**Comment by anchetaWern** [comment]
@hamchapman thanks for the quick response. I'm thinking of having the message sent in the past, with maybe some metadata that allows me to determine that this message was sent while the user was offline. Or something like a `sentAt` column which contains the date in which the message was actually sent, while `createdAt` contains the date in which the message was created in the client.

**Comment by hamchapman** [comment]
That makes sense, but I'm still not 100% sure what the actual use case is?

Is it that your chat can be replayed and you want messages to appear inline as though they were sent when a user attempted to send them?

**Comment by callum-oakley** [comment]
Closing as stale. Please [contact support](mailto:support@pusher.com) if this feature is important for your use case.
