### ISSUE TITLE
attachment.type doesn't get factored in. - PDF attachments are impossible.

### ISSUE THREAD

**Issue by rickmacgillis** [pusher/chatkit-client-js#129]
I've tried sending an attachment the way the same code that worked on the API before the major release. Now the API no longer accepts PDF attachments.

Previously the code never sent the file type, and instead allowed the API server to figure that out. I revised the code to include the type, but it doesn't matter to the server. Even hard-coding the type to `file` doesn't do anything.

To be clear, the following code doesn't function as expected, and instead sends a 422 error saying, "Attachment type is not supported. Must be one of image, video, audio or file."

This code is copied right from the software I'm building, and all variables are defined appropriately. I've added the comments for clarity on here.

```JS
var messageObject = {
			text: message,
			roomId: roomId
		};
		
		if (attachment != undefined) {

			messageObject.attachment = {
				file: attachment.file, // This is a File() object.
				name: Math.random() + '-' + attachment.name,
				type: 'file'// _getFileType(attachment.type)
			}
			
		}
```

**Comment by rickmacgillis** [comment]
@callum-oakley - Any progress on this issue?

**Comment by callum-oakley** [comment]
Hi @rickmacgillis thanks for reporting this. I've managed to reproduce it and have a good idea what's going on, will get a fix out asap.

**Comment by rickmacgillis** [comment]
Hooray! Nice work @callum-oakley. Everything works well on my end.
