### ISSUE TITLE
Limit number of people subscribed to a room

### ISSUE THREAD

**Issue by dthompson-hol** [pusher/chatkit-client-js#133]
Would it be possible in the future to add a definable limit property for the number of users subscribed to a room, to prevent additional users from subscribing to a room when running `subscribeToRoom` and returning a catch response stating why they can't subscribe to the room?

**Comment by callum-oakley** [comment]
I can certainly bring it up with the rest of the team as a feature request. What's your use case for that behaviour?

**Comment by dthompson-hol** [comment]
Great!
Having chats where it's either 2 people or a small group of people. It's possible to do it through code where you make the chat private as soon as your limit is reached using `onUserJoined` and `updateRoom`, but when two people join the room at the exact same time, there is a small window when two users can join the room and not make the room private in time and `room.users.length` both think it is within the limit. Maybe because two `onUserJoined` hooks are being ran simultaneously?, but I'm not sure about that part.

**Comment by callum-oakley** [comment]
I've moved this to our internal backlog. Please [contact support](mailto:support@pusher.com) if this is still important.
