### ISSUE TITLE
Different message received from fetchMessages than expected

### ISSUE THREAD

**Issue by dthompson-hol** [pusher/chatkit-client-js#134]
Don't know whether I am doing something stupid, but when I try to fetch a single message using `fetchMessages`, the message returned is different from the one expected. In the pseudo example below the different `console.log` id's don't match.

```
console.log("fetching message for", message.id);
currentUser.fetchMessages({
  roomId: room.id,
  initialId: message.id,
  limit: 1,
})
.then(messages => {
  console.log("recieved message for", messages[0].id);
});
```

**Comment by callum-oakley** [comment]
`fetchMessages` will fetch messages starting from `initialId`, but *excluding* the message with that `id`, so you're getting the one before it.

This is natural if you're paginating back through old messages, you know the ID of the oldest message you have, you'd like some older messages, but there's no point receiving the message you already have!

Our documentation on this could certainly be clearer... so I understand the confusion 😅

**Comment by dthompson-hol** [comment]
So without re-joining a room, what would be the easiest way to get the latest information for a message? I'm trying to determine whether a message has been deleted or not.

**Comment by dthompson-hol** [comment]
I still might be missing something, but I've had to do this below. It it would be good to have a way that you could find this data for messages that are older than the 100 message limit imposed by `fetchMessages`
```
console.log("fetching message for", newMessage.id);
this.currentUser.fetchMessages(
{
    roomId: room.id,
    limit: 100,
})
.then(messages =>
{
    let fetchedMessage = messages.find(message => message.id == newMessage.id);
    console.log("recieved message for", fetchedMessage.id);
});
```
