### ISSUE TITLE
onPresenceChanged doesn't work for when a user loses a internet connection, or should it?

### ISSUE THREAD

**Issue by dthompson-hol** [pusher/chatkit-client-js#135]
When a user loses an internet connection, any other users in that room don't receive the `onPresenceChanged` event, telling the user that the other user is now offline. Although when a user closes a tab with that chat open, the `onPresenceChanged` event does get triggered.

**Comment by callum-oakley** [comment]
How are you testing this? Note for example that ticking "offline" in the browser dev tools will not close existing websockets, and so you won't actually be seen as disconnected. Can you reproduce this if you physically disconnect your computer form the network? (disable wifi, unplug ethernet, etc)

**Comment by dthompson-hol** [comment]
We turn off the wifi on the computer.

**Comment by callum-oakley** [comment]
@dthompson-hol if you wait long enough (a couple of minutes at least) do you eventually get the event? I'm able to reproduce this to an extent, but I do get `onPresenceChanged` eventually. It looks like it might be taking us a little bit of time to detect a websocket that hasn't been cleanly closed. Thanks for bringing this to our attention.

**Comment by dthompson-hol** [comment]
@callum-oakley I've just been able to test this, and it took over 3 minutes for the update to show up once someone had disconnected their internet.

**Comment by callum-oakley** [comment]
Thanks for confirming. We have a good idea what the problem is, watch this space.

**Comment by dthompson-hol** [comment]
@callum-oakley Are there any updates on this?

**Comment by callum-oakley** [comment]
@dthompson-hol it is currently being worked on. The root cause is a fairly gnarly issue around detecting uncleanly closed websocket connections, but rest assured it hasn't been forgotten!

**Comment by dmgithb** [comment]
@callum-oakley Has this been fixed ?

**Comment by callum-oakley** [comment]
This should be working now! We improved the detection of dead websockets a little while ago and forgot to update this issue. Please let us know (ideally via [support](mailto:support@pusher.com)) if you still see this issue.
