### ISSUE TITLE
currentUser.subscribeToRoom not overwritten

### ISSUE THREAD

**Issue by dthompson-hol** [pusher/chatkit-client-js#140]
I've found in the past day or so that when you call `currentUser.subscribeToRoom` multiple times to the same room it does not get overridden any more, which it should do according to the documentation. With what we've currently got for our code, there is one scenario where it needs to call `currentUser.subscribeToRoom` more than once on the same room. But currently the hooks such as `onMessage` are being ran twice for the same room, resulting in the message appearing twice for the same chat.

**Comment by callum-oakley** [comment]
@dthompson-hol what version of the SDK are you using?

**Comment by dthompson-hol** [comment]
@callum-oakley 1.3.0

**Comment by dthompson-hol** [comment]
I've had a further look in into the problem and running
`if (typeof currentUser.roomSubscriptions[roomId] === 'undefined')`
as a check before subscribing to the room does fix the multiple hooks problem. So it does seem like a multiple subscription problem.

**Comment by callum-oakley** [comment]
I'm having trouble reproducing this. If I subscribe to a room twice it consistently replaces the existing hooks. Do you have a reproduction I could take a look at to to get a handle on what's going on?

**Comment by callum-oakley** [comment]
Just so you know how I'm testing. If I run something like

```js
alice
  .subscribeToRoom({
    roomId: "26334188",
    hooks: { onMessage: () => console.log("A") },
  })
  .then(() =>
    alice.subscribeToRoom({
      roomId: "26334188",
      hooks: { onMessage: () => console.log("B") },
    }),
  )
  .then(() =>
    alice.subscribeToRoom({
      roomId: "26334188",
      hooks: { onMessage: () => console.log("C") },
    }),
  )
```

Then I only see `C` being logged when I send new messages.

**Comment by dthompson-hol** [comment]
@callum-oakley I'll try running the code and get back to you. Or I'll see if I can simplify what i've got to reproduce the problem.

**Comment by callum-oakley** [comment]
Great, thanks.

**Comment by dthompson-hol** [comment]
@callum-oakley  I haven't had a chance to look into it properly yet, but I've just had a hunch as our code is a bit more synchronous.
If you did
```
alice
  .subscribeToRoom({
    roomId: "26334188",
    hooks: { onMessage: () => console.log("A") },
  });
alice
  .subscribeToRoom({
    roomId: "26334188",
    hooks: { onMessage: () => console.log("B") },
  });
alice
  .subscribeToRoom({
    roomId: "26334188",
    hooks: { onMessage: () => console.log("C") },
  });

```
Does it still only show `C`?

**Comment by callum-oakley** [comment]
Ahah! That reproduces the issue nicely. There must be a race condition somewhere if there's two subscriptions being made simultaneously. 😬 

Thanks for the report. Watch this space.

**Comment by callum-oakley** [comment]
@dthompson-hol this should be fixed in 1.3.1. Thanks for your help debugging.

**Comment by rogsmith** [comment]
I am having this issue, but it is not  race condition. The scenario is that a user can belong to multiple rooms. If they enter room A and then subscribe to that room, they receive 1 update per message for room A, if they leave room A and then come back, it seems they will be subscribed again and then will receive 2 updates per message sent to room A and so forth. Maybe I am using this incorrectly.

**Comment by bighitbiker3** [comment]
@callum-oakley I've run into this problem with both `subscribeToRoom` and `subscribeToRoomMultipart` on `1.9.1` and now `1.11.0`.  I'm trying to figure out a workaround/easily repro example. Will report back

**Comment by callum-oakley** [comment]
Sorry to hear that! A reproduction would be a great help to us, thanks.

**Comment by bighitbiker3** [comment]
@callum-oakley Sorry for the delay! Here's the reproduction repo

https://github.com/bighitbiker3/chatkit-repro

Let me know if you have any questions at all!
