### ISSUE TITLE
[ INFO REQUIRED ] Check if a room exist already by room name ?

### ISSUE THREAD

**Issue by rajat-np** [pusher/chatkit-client-js#148]
Is there a way by which I can figure out if the room already exists in my chatkit instance ?

Eg- If there is a room general, then I should be able to know that room General exists and there is no need to recreate it.

**Comment by rajat-np** [comment]
I was able to cater this requirement, by getting all rooms i.e rooms which user has joined already and rooms which a user can join. After getting them all, I compared the names. But this makes the chatroom takes longer time to load. 
If there some othe approach I can use or some built-in functionality to cater this ?

**Comment by callum-oakley** [comment]
We would like to solve this problem eventually by allowing you to provide your own room IDs, though at the moment there's no way to look up a room by name, so your workaround is the correct approach for now.

**Comment by rajat-np** [comment]
Ok, thanks for the info.
