### ISSUE TITLE
Having hard time installing SDK

### ISSUE THREAD

**Issue by rtdk0324** [pusher/chatkit-client-js#149]
When trying to install chatkit by typing -> npm install @pusher/chatkit-client , these warnings show.. I don't know how to solve this issue. Please help...

npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by callum-oakley** [comment]
Hi @rtdk0324! ts-pnp is not a dependency of @pusher/chatkit-client (it must be coming from something else in your project?), and fsevents is an optional dependency that you don't need on windows. It's annoying that npm gives you these noisy warnings but you can safely ignore them. :)

**Comment by jakeruleaux** [comment]
Just FYI. I have having the same issue setting up a basic react app with react drop-zone

**Comment by quanganhhoang** [comment]
Fyi, I have the same issue but only got the first warning (requires a peer of typescript@*) but from what I have read on various sources, it is safe to ignore that message. Though I got another warning about 63 vulnerabilities that need manual review!?

**Comment by tomhosker** [comment]
I'm having literally the same issue as you, @quanganhhoang. Did you get anywhere in solving it?
