### ISSUE TITLE
Embedding metadata in messages

### ISSUE THREAD

**Issue by farkob** [pusher/chatkit-client-js#152]
Is there a way to embed metadata in the messages? I need to add a unique id to messages so I can show them in "sending" state and then later replace it with the one that comes from the ChatKit. If we wait for the roundtrip, UX lacks the instant feeling. Also this way we can provide a mechanism for sending failed messages later.

I thought of encoding in the message itself but that feels wrong to me.

**Comment by callum-oakley** [comment]
There certainly is! If you're using the latest version of the SDK, you can use the [`sendMultipartMessage`](https://docs.pusher.com/chatkit/reference/javascript#sending-a-message) function to send a message with multiple "parts" of whatever type you want. One of those parts could be a JSON blob with some metadata in it. This might look something like

```js
currentUser.sendMultipartMessage({
  roomId: room.id,
  parts: [
    {
      type: "text/plain",
      content: "Your actual message content.",
    },
    {
      type: "application/json",
      content: JSON.stringify({
        your_id: "foo",
      }),
    },
  ],
})
```

Then `subscribeToRoomMultipart` or `fetchMultipartMessages` will return messages [in the multipart format](https://docs.pusher.com/chatkit/reference/javascript#messages).

**Comment by farkob** [comment]
@callum-oakley Thanks!
