### ISSUE TITLE
No Connection Error When uploading image from android

### ISSUE THREAD

**Issue by Kiran0791** [pusher/chatkit-client-js#153]
Trying to upload file using react native. On IOS it's working fine. But on android it's Unable to upload to room with No Connection error. Below the method used
    this.currentUser.sendMessage({
      roomId: CHATKIT_ROOM_ID,
      text: ' ',
      attachment: {
        file: {
          uri: res.path,
          type: 'image/jpeg',
          name: res.name,
        },
        name: res.name,
      }
    })
    .then(messageId => {
      
      console.log(`Added message `)
    })
    .catch(err => {
  
      console.log(`Error adding message: ${err}`)
    })
  }

**Comment by Kiran0791** [comment]
I figured it out. We need to pick **res.uri** instead if **res.path**. Which works on both the platform.

**Comment by callum-oakley** [comment]
Glad you got to the bottom of it. Thanks for updating. :)
