### ISSUE TITLE
subscribeToRoomMultipart Issue

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#154]
Good day! Yesterday start to get errors when fetching messages by subscribeToRoomMultipart method. The old one is working fine. 5 days ago had no errors.

**Comment by callum-oakley** [comment]
Oh no! What errors exactly?

**Comment by callum-oakley** [comment]
Scratch that. We've found the problem and will have a fix out very shortly. It's purely a server side issue. Sorry about this!

**Comment by callum-oakley** [comment]
Should be fixed now.

**Comment by alexey13** [comment]
Fixed. Thanks!
