### ISSUE TITLE
Typo in react messaging chatkit

### ISSUE THREAD

**Issue by paulokuda** [pusher/chatkit-client-js#168]
Not sure if this is the best repo to post in, but just wanted to flag this for your team

Url: https://pusher.com/tutorials/messaging-react-chatkit

![image](https://user-images.githubusercontent.com/6726318/57497866-547e5a00-728e-11e9-909a-45e80eb1c3df.png)

**Comment by callum-oakley** [comment]
Thanks for this (and sorry for the very delayed response), we've raised it with the relevant people.
