### ISSUE TITLE
Issue with subscribeToRoomMultipart

### ISSUE THREAD

**Issue by nomadme** [pusher/chatkit-client-js#170]
whenever we used this upgraded version over the `subscribeToRoom` then the `message.text` is being undefined.

**Comment by Alex-231** [comment]
Message.text is part of the legacy message type (v2 API). 
With subscribeToRoomMultipart, the message text is is store within a part.
Message.parts[].payload.content where Message.parts[].payload.type == "text/plain".

**Comment by minaorangina** [comment]
This seems resolved, so closing. If there's still a problem please contact support@pusher.com for more direct help
