### ISSUE TITLE
Typing indicator is not working

### ISSUE THREAD

**Issue by nomadme** [pusher/chatkit-client-js#171]
Hello,

Just followed the documentation on:`https://pusher.com/docs/chatkit/reference/javascript#receive-typing-indicator-events`, but unable to make this work.

This is what I have:
```
...
return currentUser
        .subscribeToRoom({
            roomId: `${id}`,
            messageLimit,
            hooks: {
                onMessage: message => {
                    this.messages = [...this.messages, message];
                },
                onUserStartedTyping: user => {
                    console.log(`User ${user.name} started typing`)
                },
                onUserStoppedTyping: user => {
                    console.log(`User ${user.name} stopped typing`)
                }
            },
        })
        .then(currentRoom => {
            this.currentRoom = currentRoom;
        });
```

**Comment by amitpatil321** [comment]
I am also facing the same issue, `onUserStartedTyping` never gets triggered. Guys, can you please check if this feature has stopped working?

**Comment by amitpatil321** [comment]
Any updates on this? I am still not able to see "onUserStartedTyping" working

**Comment by MarkHinojosa** [comment]
Thought I was the only one! Is there a typing indicator in the Console hidden somewhere?

**Comment by amitpatil321** [comment]
@MarkHinojosa : You mean its working for you ?

**Comment by MarkHinojosa** [comment]
@amitpatil321 it Is Not working for me

**Comment by amitpatil321** [comment]
@pusher : Guys, please fix it asap, Initially I thought that something is wrong with my setup but now it's confirmed that its code issue.

**Comment by callum-oakley** [comment]
Sorry for the delay on this. I can't immediately reproduce, but will try the exact snippet located above later and report back. Watch this space!

**Comment by callum-oakley** [comment]
How are you testing this? If I run the exact snippet above, then with a different user call

```js
someOtherUser.isTypingIn({ roomId: id })
```

I reliably get both `onUserStartedTyping` and `onUserStoppedTyping` firing.

One thing to make sure of is that you do use a different user, since you will never receive your own typing indicators.

**Comment by amitpatil321** [comment]
Yes i have 4 users, I will give it a try again. May be i missed this thing "since you will never receive your own typing indicators."

**Comment by AllexNogue** [comment]
Mesmo problema aqui, isso ja foi resolvido?

**Comment by minaorangina** [comment]
Closing the issue as it's stale. If this is still a problem feel free to reopen, or contact support@pusher.com where one of our team can give dedicated help.
