### ISSUE TITLE
Android (React Native) - App Crashes after being inactive for a while

### ISSUE THREAD

**Issue by s5963028** [pusher/chatkit-client-js#177]
I have a React Native application both for Android & IOS.

When I open the Android App and don't tap anything for 10-15 seconds, app crashes.

![image](https://user-images.githubusercontent.com/5329602/59015644-21f15e00-8848-11e9-98ef-bce0fa408166.png)

I receive a message about handleUserSubReconnection but there is no info about it at all...
I already set the logger to console.log instead of console.error.

react-native: 0.56
chatkit-client: 1.5.0

**Comment by s5963028** [comment]
Any idea? ⏲

**Comment by callum-oakley** [comment]
Hi @s5963028, sorry for the delay.

Looks a lot like you're seeing [this React Native bug](https://github.com/facebook/react-native/issues/15902#issuecomment-373964965). What version of React Native are you using, and do any of the workarounds listed on the linked issue work for you?

**Comment by s5963028** [comment]
Thanks, @callum-oakley!
