### ISSUE TITLE
How do you update roomId dynamically

### ISSUE THREAD

**Issue by niyaazparker** [pusher/chatkit-client-js#179]
i  would like to update the below roomID with dynamic string so that it populates based on user that signs in, it will fetch the room id in which the user belongs to

return currentUser.subscribeToRoom({
                          roomId: "31227269",
                          messageLimit: 100,
                          hooks: {
                            onMessage: message => {
                              this.setState({
                                messages: [...this.state.messages, message],
                              })
                            },
                            onUserStartedTyping: user => {
                                              this.setState({
                                               usersWhoAreTyping: [...this.state.usersWhoAreTyping, user.name],
                                             })
                                            },
                                            onUserStoppedTyping: user => {
                                              this.setState({
                                                usersWhoAreTyping: this.state.usersWhoAreTyping.filter(
                                                  username => username !== user.name
                                                ),
                                              })
                                            },
                                            onPresenceChange: () => this.forceUpdate(),
                          },
                           
                        }

**Comment by Alex-231** [comment]
I don't think this is a chatkit issue, the interface seems to provide what you need to do that.
The CurrentUser has a rooms property which contains a list of the rooms they've joined.
You can use this list to join one of the user's rooms.

I would suggest something like this.

```
return currentUser.subscribeToRoom({
    roomId: currentUser.rooms[0].id,
    messageLimit: 100,
    hooks: {
    onMessage: message => {
        this.setState({
        messages: [...this.state.messages, message],
        })
    },
    onUserStartedTyping: user => {
        this.setState({
        usersWhoAreTyping: [...this.state.usersWhoAreTyping, user.name],
        })
    },
    onUserStoppedTyping: user => {
        this.setState({
        usersWhoAreTyping: this.state.usersWhoAreTyping.filter(
            username => username !== user.name
            ),
        })
    },
    onPresenceChange: () => this.forceUpdate(),
    },
}
```

**Comment by minaorangina** [comment]
This seems to be resolved, will close the issue. Get in touch at support@pusher.com if you need more help
