### ISSUE TITLE
failed "yarn lint:build:test"

### ISSUE THREAD

**Issue by rranranrrr** [pusher/chatkit-client-js#188]
src/main.js → dist/web/chatkit.js...
[!] Error: 'sendRawRequest' is not exported by node_modules/_@pusher_platform@0.16.2@@pusher/platform/dist/web/pusher-platform.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/token-provider.js (1:9)
1: import { sendRawRequest } from "@pusher/platform"
            ^
2:
3: import { appendQueryParams, typeCheck, unixSeconds, urlEncode } from "./utils"

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by callum-oakley** [comment]
I can't reproduce. Which version are you on? Do you have any output from `git diff`?

**Comment by minaorangina** [comment]
Closing as stale, please re-open if still an issue, or contact us via support@pusher.com for more direct help
