### ISSUE TITLE
Error message on `new TokenProvider`

### ISSUE THREAD

**Issue by rrcobb** [pusher/chatkit-client-js#2]
When I create a TokenProvider to pass to a chatmanager for auth, it will silently fail if there is not an `authContext: { queryParams: {} }` key provided. This should probably work or fail more loudly.

```
const tp = new TokenProvider({
    url: 'some_token_route',
    userId: 'some_user_id',
  });

const cm = new ChatManager({
    instanceLocator: ENV['INSTANCE_LOCATOR'],
    tokenProvider: tp,
  });

// silently fails, doesn't make a network request
cm.connect({
  delegate: {},
  onSuccess: (currentUser) => {
     console.log('good connection', currentUser);
  },
  onError: (error: string) => {
     console.error('could not connect this time', error);
   },
});
```

**Comment by hamchapman** [comment]
As with #3 apologies for not seeing this sooner. You're spot on again and I think we've already fixed this one with the 0.1.1 release.

Thanks again for the report!
