### ISSUE TITLE
Error uploading a video attachment

### ISSUE THREAD

**Issue by johanquiroga** [pusher/chatkit-client-js#200]
I'm getting an error when trying to send a video as an attachment:

![image](https://user-images.githubusercontent.com/22845267/63059055-fcba4500-beb3-11e9-9f5d-d5ab01bf88fd.png)

Video of the error: https://cl.ly/5f0e7b

## @pusher/chatkit-client
v1.11.0

## React Native Environment Info:
  * System:
    - OS: macOS 10.14.6
    - CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    - Memory: 26.60 MB / 16.00 GB
    - Shell: 5.7.1 - /usr/local/bin/zsh
  * Binaries:
    - Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    - Yarn: 1.17.3 - /usr/local/bin/yarn
    - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    - Watchman: 4.9.0 - /usr/local/bin/watchman
  * SDKs:
    - iOS SDK:
        - Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    - Android SDK:
        - API Levels: 23, 25, 27, 28
        - Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  * IDEs:
    - Android Studio: 3.3 AI-182.5107.16.33.5314842
    - Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  * npmPackages:
    - react: 16.6.3 => 16.6.3 
    - react-native: ^0.58.6 => 0.58.6 
  * npmGlobalPackages:
    - react-native-cli: 2.0.1
    - react-native-git-upgrade: 0.2.7

**Comment by vivangkumar** [comment]
Hey @johanquiroga could you please raise this as a ticket to support@pusher.com please?

**Comment by johanquiroga** [comment]
Sure, thanks @vivangkumar
