### ISSUE TITLE
Android SDK setReadCursor trouble

### ISSUE THREAD

**Issue by eugenCodreanu** [pusher/chatkit-client-js#201]
Hi. I have implemented pusher chatkit on IOS and android.
On android (kotlin) I connected to chat and receive the currentUser. Setup chat listener's.
That I observe that listeners works perfectly until I use currentUser.setReadCursor function. 
After this it set the cursor but chat listener's don't fire anymore :(
Witch can be the issue? Can you check this.Thanks

**Comment by callum-oakley** [comment]
Can you please open this issue on the Android SDK or reach out to support? Closing since this isn't an issue with the JS SDK.
