### ISSUE TITLE
Can you add babel env preset in esm build ?

### ISSUE THREAD

**Issue by bogdand92** [pusher/chatkit-client-js#210]
Hi guys, 
We using webpack and  uglify-js and we can’t build our app after upgrading from `1.4.0` to `1.13.0`, because of version `1.13.0` is no longer compatible with es5.
In order to use uglify-js all our dependencies must be es5 compatible.

We found a commit which break es5 support: [commit](https://github.com/pusher/push-notifications-web/commit/e238a4cca12b98f94e515b7a554089550aaf9529#diff-10bbeaf7c987499a2d7bbf02f26c7c88)
Rollup build of `@pusher/push-notifications-web` was splitted into separate esm and cdn, and esm version is not using babel-preset-env anymore. Can you bring back es5 support to `@pusher/chatkit-client`?

uglify-js  for 1.6.1 version and 1.13.1 [video](https://i.imgur.com/apzQDnA.mp4)

Thanks for watching

**Comment by bogdand92** [comment]
<img width="646" alt="Screenshot 2019-09-26 at 16 15 51" src="https://user-images.githubusercontent.com/4055317/65675859-120cbc80-e079-11e9-8680-69f288d3c73e.png">

**Comment by callum-oakley** [comment]
thanks a lot for this @bogdand92 . we'll take a look asap.

**Comment by callum-oakley** [comment]
fixed in 1.13.4 (apologies for the delay, this one got lost somewhere along the way...)
