### ISSUE TITLE
trouble with hook onNewReadCursor

### ISSUE THREAD

**Issue by tstocker** [pusher/chatkit-client-js#214]
Hello. 
I'm working on a app using chatkits hooks on cursors. 
chatkit version : @pusher/chatkit-client@1.11.0

setReadCursor is call when a user open a room or send a message.
Then we catch the cursor with the hook onNewReadCursor 

```
this.chatManager.connect({
  onNewReadCursor: cursor => {
    console.log('onNewReadCursor');
    messageReader(cursor.roomId).then(receipts => {
      store.dispatch(updateRecipients({ cursor: cursor, receipts: receipts[0] }));
    }).catch(err => { console.err(err); });
  },
});
```

All was working fine each time, till we merge the code to an other branch. Code is the same on each branch for chatkit cursor usage.
onNewReadCursor is never called on the new branch, i can't see any log in onNewReadCursor callback, others hooks works.

Is their any trouble with onNewReadCursor ?
If you need more details don't hesitate.
can you help me please on that subject ? Thanks

**Comment by callum-oakley** [comment]
@tstocker you mentioned it was working before a merge, it sounds like something in the merge must have broken it. Have you confirmed that the `setReadCursor` call is still happening in the merged code?

**Comment by tstocker** [comment]
thanks you send me in the right way looks their was some change in the object structure we send on setReadCursor. works now
