### ISSUE TITLE
services/chatkit/user_already_exists now called services/chatkit/bad_request/user_already_exists

### ISSUE THREAD

**Issue by xxRockOnxx** [pusher/chatkit-client-js#215]
it's leaves me wondering why my app wasn't working right when I didn't change anything, only to figure out the `error` code was changed and no announcement or even list of errors in documentation is available.

Please consider notifying your users and document this as well. It's pretty annoying.

It's not related to this library as it is a server thing, but I can't find a right place to report this or even how to contact Pusher about this.

**Comment by luismfonseca** [comment]
@xxRockOnxx sorry about this. This was an internal refactoring on the error-handling code with unintended consequences.

We will be reverting this change ASAP.
