### ISSUE TITLE
Issues with subscribing to rooms 

### ISSUE THREAD

**Issue by shaunclark5649** [pusher/chatkit-client-js#217]
I keep getting error messages when trying to subscribe to the room 

`Error: attempt to connect a cancelled room subscription`

but if I try to get the user information from a room without subscribing I get an error telling me I cannot access the data until I subscribed ?? 

` Must be subscribed to room ***************************  to access users property`

this is really confusing me right now

`
              this.props.chatkit.currentUser.subscribeToRoom({
                roomId: this.props.chatkit.currentUser.rooms[0].id,
                messageLimit: 20,
                hooks: {
                  onAddedToRoom: roomdata => {
                    console.log(`Added to room ${roomdata.name}`);
                  }
                }
              });
`

**Comment by minaorangina** [comment]
Hi, if this is still a problem please contact our support team at support@pusher.com. Otherwise will close the issue
