### ISSUE TITLE
SyntaxError: unexpected token { (chrome 48)

### ISSUE THREAD

**Issue by baversjo** [pusher/chatkit-client-js#221]
Hello, we need to support some older chrome clients due to android 4.4 support. Specifically, chrome 48.

In a recent update from pusher/chatkit-client@1.5.0 to pusher/chatkit-client@1.13.3, a (newer) js syntax seems to have maybe slipped into chatkit? See attached error:

![image](https://user-images.githubusercontent.com/371678/72179350-030e0800-33e5-11ea-859e-0321ad36d394.png)

**Comment by callum-oakley** [comment]
Hi @baversjo, I think we tracked down the change that introduced this. Can you try with 1.13.4 and let me know if the problem persists?

**Comment by baversjo** [comment]
@callum-oakley can confirm it works perfectly on chrome 48 now, thank you for your speedy resolution!

**Comment by callum-oakley** [comment]
Good stuff! Thanks for following up. :)
