### ISSUE TITLE
WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by vinayp21** [pusher/chatkit-client-js#223]
WebSocket connection to 'wss://us1.pusherplatform.io/ws' failed: Error during WebSocket handshake: Unexpected response code: 403

Getting this error whenever I am trying to connect using ChatManager.connect function.

trying to establish connection through localhost 

code -

 const tokenProvider = new TokenProvider({
      url: TOKEN_URL,
    })
    
    const chatManager = new ChatManager({
        instanceLocator: INSTANCE_LOCATOR,
        tokenProvider: tokenProvider,
        userId:'test' // a valid user created in console
      })
     const currentUser = await chatManager.connect();

**Comment by minaorangina** [comment]
Hi, if this is still an issue please let our support team know at support@pusher.com, and they can give you more direct help.
