### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'o[s]=n[s]')

### ISSUE THREAD

**Issue by krismeld** [pusher/chatkit-client-js#225]
```
TypeError node_modules/@pusher/chatkit-client/dist/react-native/chatkit.js:1
undefined is not an object (evaluating 'o[s]=n[s]')
```

About once a day this error shows up in our bugsnag log, we cannot recreate it locally, do you maybe know why this happens and how it can be fixed?

**"@pusher/chatkit-client": "^1.13.3"
"react-native": "0.61.5"**

**Comment by minaorangina** [comment]
Hi, it's possible that the library is trying to reference something that isn't available in the React Native environment, but there isn't enough information here for us to debug on our side. If you have any more context as to when this error appears, please let us know
