### ISSUE TITLE
[Feature] Integration with pusher notifications

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#30]
Good day! It would be awesome to notificate users of new messages if they are offline or unactive. Examples with such integration are welcome. And i have to say i like pusher very much. Tried with firechat firebase but chatkit for me:)

**Comment by gildebrand** [comment]
@alexey13 the feedback I got from the Pusher team about this is that it will come, but for now we will have to implement it ourselves. I shared the solution I went for in GitHub: https://github.com/gildebrand/chatkit-push-helper

**Comment by alexey13** [comment]
Wow its awesome. Will get deeper in your solution. Big thanks for share

**Comment by teminer** [comment]
@gildebrand hope you don't mind I've been sharing that with pretty much everyone who asks me about this integration (whom I'd otherwise have to disappoint with "not yet") :)

Huge thank you for doing this!

**Comment by gildebrand** [comment]
@teminer cool 😄 
I'll probably update the repository with some simple instructions to help newcomers get going!

**Comment by alexey13** [comment]
@gildebrand its made using RxJS right?

**Comment by gildebrand** [comment]
@alexey13 thats right!

**Comment by gildebrand** [comment]
Update: provided my repo with a Readme to help people get going 😄

**Comment by neuropass** [comment]
Again a must have for chatkit. Would benefit cross integration for pusher services anyway.

**Comment by vivangkumar** [comment]
@neuropass Push notifications is on the way (integrated into chatkit) :)

**Comment by tribeAppMobile** [comment]
Already integrated ? on pusher.com web it shows that the integration already in beta version ?

**Comment by teminer** [comment]
@tribeAppMobile Yes! It was released just last Friday for Android & iOS. :)

A solution for react native is on the way.

**Comment by aferrando** [comment]
Any updates? It would be great to have push notifications on react native

**Comment by Kiran0791** [comment]
Any update on react native push notification integration

**Comment by parthawasthi** [comment]
Hi all.

We appreciate that this has been a long-awaited feature for many of you — we are looking at shipping browser notifications later this year. The reason this feature request has been such a long time coming is that we have been working to ensure mobile push notifications provide a great experience before we move to support browser notifications. 

Over the course of 2018, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.

We thank you for your patience and continued support.

Parth

**Comment by viniciusfont** [comment]
Hi @parthawasthi , thanks for the reply. And regarding the integration of mobile push notifications with React Native (this integration already exists for Android and native iOS), will we have an integration, or will push notifications only work for those who used the native library? Remembering that the JS client can be used by mobile apps.
