### ISSUE TITLE
Create room 404 error One or more User IDs were not found

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#32]
Good day!

Making this:
currentUser.createRoom(
  {
    name: "hi room",
    addUserIds: [curus, authorName],
  }

Getting that:
One or more User IDs were not found.
Error creating room SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Ids of users
curus = boy11
authorName = girl-13-11

**Comment by vivangkumar** [comment]
Hi!

Have you ensured that you've created the users whose ID's you've passed to `addUserIds`?

The error is a result of not being able to find the users that you're trying to add to the room. If you've not created them, then you should be creating those users first before making the call to `createRoom`

**Comment by alexey13** [comment]
Yes, you are right problem those users not created. Made it and got 500 error "Failed to create room". Api said to wait and try again. Will wait.

**Comment by alexey13** [comment]
Tried to create without addUserIds and it work. Hmm, any ideas?

**Comment by alexey13** [comment]
Found a reason. In addUserIds i used currentUser id.
