### ISSUE TITLE
getAllRooms private rooms not in the list

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#33]
Good day! Can someone test it. Only i dont get private rooms in array?

**Comment by alexey13** [comment]
Created public room its in the list of getAllRooms, created private room its not in the list

**Comment by alexey13** [comment]
Update. To get all rooms that user is a member need to use currentUser.rooms

**Comment by hamchapman** [comment]
@alexey13 using `currentUser.rooms` is definitely the expected method of interacting with the list of rooms that the current user is a member of, whether private or public. 

I believe the intention of `getAllRooms` was to let a user get a list of all of the rooms that they are a member of as well as all of the their "joinable" rooms (i.e. public rooms that they are not currently a member of). Whether or not this is something that's ever useful is a good question though and I expect the answer is no!

@hot-leaf-juice I know you've been looking at this sort of stuff lately - do you agree with the opinion above that we should remove `getAllRooms`?

**Comment by alexey13** [comment]
@hamchapman when user create private room getAllRooms not show that room in his list, plus it show only 20 rooms. So i choose getJoinableRooms + currentUser.rooms

**Comment by hamchapman** [comment]
Interesting. That sounds like it's likely a bug, and only further fuels my desire to remove it.

We've also discussed having `joinableRooms` as a property like `rooms`, on `currentUser`, that gets updated as new public rooms are created. So with the combination of those two properties it would be trivial to have a list of all rooms that the current user is either a member of or could join that gets updated as appropriate.

**Comment by vivangkumar** [comment]
@hamchapman I also think we don't have pagination support for that endpoint yet..in the js library.

**Comment by hamchapman** [comment]
Yeah, I'm not sure we do in any of SDKs as it's not been a priority. It's only serving to confuse at the moment. Let's remove it.

**Comment by alexey13** [comment]
@hamchapman I can close thread?
