### ISSUE TITLE
seems a bug in "userStartedTyping: (user)", "user" returning room data instead of user

### ISSUE THREAD

**Issue by webreinvent** [pusher/chatkit-client-js#36]
```js
chatManager.connect({
	delegate: {
	    userStartedTyping: (user) => {
	    	//user should have data of the user who is 
	    	//currently type instead it has data of the room
	    	console.log(`User ${user.name} started typing in room`);

		}
    },
});
```

Here are  the screenshots to help: 
https://i.imgur.com/J6Y62Hj.png
https://i.imgur.com/leIJjyW.png

Let me  know if you can help

**Comment by alexey13** [comment]
Dont see room in your code. But it should be.
``chatManager.connect({
  delegate: {
    userStartedTyping: (room, user) => {
      console.log(`User ${user.name} started typing`);
      startedTyping(user.name);
    },``

**Comment by webreinvent** [comment]
@alexey13 
I was referring to your documentation https://i.imgur.com/2S3T5nO.png

**Comment by alexey13** [comment]
You used it in wrong place.
With room in ChatManagerDelegate.
Without room in RoomDelegate

https://docs.pusher.com/chatkit/reference/javascript#receiving-typing-indicator-events
https://docs.pusher.com/chatkit/reference/javascript#chatmanagerdelegate

**Comment by webreinvent** [comment]
Oh okay, got it. 
Thanks. 
Although, I still feel the documents is complicated & sometimes confusing.
