### ISSUE TITLE
Room name

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#37]
When user create private 1 on 1 room i would like to show as name of that room name of other user.
For example user 1 { id: man11, name: Alex }, user 2 { id: women3, name: Violet }. User 1 should see "Violet" as name of room, user 2 "Alex".
Now i can set only id as room name of other person by using rooms -> userIds.filter(userId => userId != own.userid)
Is there a way to get a name of user? I see it deeper in userStore

**Comment by hot-leaf-juice** [comment]
Getting it out of the `userStore` is your best bet at the moment I think yes. Similarly to with presence, in the next release the room object will have a `users` property which will have a list of all the users, names and all. Sorry that I can't be more helpful immediately!

**Comment by hamchapman** [comment]
As @hot-leaf-juice said this will be fixed in the soon-to-be-released new version of the SDK.

**Comment by abkr08** [comment]
I'm having this issue and I can't even access the userIds array.

**Comment by callum-oakley** [comment]
@abkr08 what specifically are you trying to do? You should be able to see users on a room (including their names) by [accessing the `users` property](https://docs.pusher.com/chatkit/reference/javascript#room-properties).

**Comment by abkr08** [comment]
I am trying to do what @alexey13 was trying to do. Get a private room's name to show the other participant's name for each user. 
`const contacts = this.props.chatkitUser.rooms.map(room => {
                console.log(room.users); //logs an empty array to the console
                let obj = {};
                obj.name = !room.isPrivate ? room.name :
                room.userIds.filter(name => name !== this.props.userId); //For public rooms, it works alright, //but for the private rooms, it doesn't. The userIds array seems to be empty
                obj.id = room.id;
                return obj;
            });
 console.log(contacts); //Logs this array: 
0: {name: "Gouyu", id: "19377517"}
1: {name: Array(0), id: "19377983"}
2: {name: Array(0), id: "19378926"}
3: {name: "", id: "19379188"}`

**Comment by abkr08** [comment]
Hey @callum-oakley  any idea why this is happening?

**Comment by callum-oakley** [comment]
@abkr08 you can only see the users in a room if you are subscribed to that room, `room.users` should throw an error if you aren't subscribed. Then again, `room.name` should always be populated? What do you get for `room.name` if the room is private?

**Comment by abkr08** [comment]
> When user create private 1 on 1 room i would like to show as name of that room name of other user.
> For example user 1 { id: man11, name: Alex }, user 2 { id: women3, name: Violet }. User 1 should see "Violet" as name of room, user 2 "Alex".
> Now i can set only id as room name of other person by using rooms -> userIds.filter(userId => userId != own.userid)
> Is there a way to get a name of user? I see it deeper in userStore

@callum-oakley `room.name` and `room.id` give correct details, but like this quoted post, I want to access the userIds array to get the other user's name
