### ISSUE TITLE
Offline until send first message

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#40]
Hi to all! I have same bug. You can see it here too https://github.com/pusher/chatkit-demo
Connect as user, after connect another account. Until you send message you not get status online. If you not understood what i talking about i can show

**Comment by hamchapman** [comment]
To check if I understand, is this what you're saying:

* User A connects to Chatkit
* User B connects to Chatkit

At this point you'd expect user B to have their presence state set as online and so user A's client should show this. Similarly, user A should show as online to user B.

However, you're saying that this isn't the case, at least not until one of the users (which one?) sends a message?

If you could send a gif or something like that then that would great and much appreciated!

**Comment by alexey13** [comment]
Sorry for delay. https://www.dropbox.com/s/edu15i4n5h7vuuw/ice_video_20180310-095813.webm?dl=0

**Comment by alexey13** [comment]
@hamchapman i hope you understand what i mean, if not let me know please

**Comment by hamchapman** [comment]
Hey @alexey13 thanks a lot for the video - definitely makes sense.

We have taken a look and this appears to be a UI bug with the demo, at least if you're using the latest version of the demo. I've created a ticket in our system to investigate the bug in the demo and that should be fixed soon.

You can check this for yourself if you load up the demo and check the user list (click the icon in the top right) and you should be able to see that users show up with appropriate presence information (the little green circle if online) before any messages are sent by anyone.

I'll close this as an issue for now as it doesn't appear to be a bug with the SDK itself. 

Thanks a lot for the report and let us know if this doesn't reflect what you're seeing 👍
