### ISSUE TITLE
503 responses causing SyntaxErrors on chatkit js

### ISSUE THREAD

**Issue by iMerica** [pusher/chatkit-client-js#44]
Two separate issues:

- 503 errors. Example: GET https://us1.pusherplatform.io/services/chatkit/v1/XXX/users/XXX [503]
- Not handling error states gracefully

**Comment by hamchapman** [comment]
Hey @iMerica could you expand on what you mean by 

> Not handling error states gracefully

if possible?

The upcoming release of the SDK should massively improve error handling seeing as there was a recently fixed bug with the underlying `pusher-platform-js` SDK which didn't properly reject the promises of failed requests in all cases.

**Comment by iMerica** [comment]
Handling Errors Gracefully: 
- Handle every possible networking failure.
- Handle every possible application failure (like receiving non-JSON).
- Don't totally crash the program
- Maybe retry as needed.
- Keep track of the retry counts.
- Explicit Exception classes 

A syntax error indicates that a particular scenario was unanticipated and will cause the app to crash.

**Comment by hot-leaf-juice** [comment]
Hi @iMerica the error handling story should be much improved in 0.7.X. In particular you shouldn't be getting syntax errors on unsuccessful responses any more. Feel free to re-open if anything new crops up.

**Comment by iMerica** [comment]
Thanks @callum-oakley. We appreciate your work on this!
