### ISSUE TITLE
currentUser.createRoom() addUserIds does not fire the addedToRoom event

### ISSUE THREAD

**Issue by gileswells** [pusher/chatkit-client-js#5]
When creating a new chat room and adding user_2 to it using the `addUserIds` method the `addedToRoom` event doesn't fire in user_2's websocket.
```
currentUser.createRoom(
    {
        name: "aol_chat_room",
        addUserIds: ['user_2']
    },
    function (room) {},
    function (error) {}
);
```

In order to get it to fire you'd need to add the user to the chat room after the room is created in the success callback like so.
```
currentUser.createRoom(
    {
        name: "aol_chat_room",
    },
    function (room) {
        Laravel.chatkit.currentUser.addUser(
            'user_2',
            room.id,
            function (room) {},
            function (error) {}
        );
    },
    function (error) {}
);
```

I would expect that regardless of how someone is added to a room, either at creation or moments after, both would fire the addedToRoom event.

**Comment by hamchapman** [comment]
That sounds like a bug as the behaviour you've described is how it should be working. I'll take a look at what's going on and get back to you.

**Comment by hamchapman** [comment]
Just to keep you updated, I tested this and it doesn't seem to be an issue with this SDK but in fact with the service itself. We'll should have a fix for it tomorrow if all goes well! 

Thanks for the report. I'll update this when it's fixed.

**Comment by gileswells** [comment]
@hamchapman I suspected it was with the backend service but didn't know if there was a better place to report it. Thanks for the update.

**Comment by vivangkumar** [comment]
@gileswells I've just created a PR for our server side and is up for review tomorrow morning when we're all back at work. We'll ping you when its all merged in and good to go!

**Comment by vivangkumar** [comment]
@gileswells We've just pushed out a fix and tested with the JS SDK. Hopefully it should all be working as expected. Thanks for reporting this issue.

**Comment by gileswells** [comment]
I see it working on my end as well. Thanks for the quick fix @vivangkumar!
