### ISSUE TITLE
0.7.0 typing

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#54]
Good day to all! Trying to get it that way:
`  .connect({
  	onStartedTyping: (room, user) => console.log('type'),
  })`
But its not working.

**Comment by hot-leaf-juice** [comment]
Hi @alexey13 it should be `onUserStartedTyping`, looks like there was a typo in the changelog, sorry about that! We'll have 0.7.0 officially released soon and then the new docs will be available.
