### ISSUE TITLE
Create room with users then subscribe all members?

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#56]
Good day, friends! This scenario impossible right?
Example:

```
currentUser.createRoom({
      name: chatname,
      private: true,
      addUserIds: [authorName]
})
.then(room => {

      currentUser.subscribeToRoom({
        roomId: room.id,
      })

     authorName.subscribeToRoom({
        roomId: room.id
     })
})
```

Why i need that? When second user unsubscribed he not get messages from room and his presense.state not reachable.

**Comment by alexey13** [comment]
Found solution using addedtoRoom hook on side of added user.

**Comment by hot-leaf-juice** [comment]
Sounds like you found a solution, thanks for the update :)
