### ISSUE TITLE
NPM registry versions behind

### ISSUE THREAD

**Issue by gildebrand** [pusher/chatkit-client-js#62]
I'm not fully invested in the logic behind how the NPM registry works, but through NPM I can't install any version prior to 0.6.2, and I can see that there are a couple of releases since that version.

**Comment by callum-oakley** [comment]
Hi @gildebrand, we moved the package from `pusher-chatkit-client` to [`@pusher/chatkit`](https://www.npmjs.com/package/@pusher/chatkit), so to get `0.7.X` and above you will have to switch over to `@pusher/chatkit`.

Sorry for the confusion! We've now added a deprication notice to `pusher-chatkit-client` to point people towards the new package in the future.
