### ISSUE TITLE
[Feature] Add support for cleared typing event

### ISSUE THREAD

**Issue by gileswells** [pusher/chatkit-client-js#64]
Currently we have the `onUserStartedTyping` and `onUserStoppedTyping` which both work just fine. I can however see a scenario where a user like myself would want to know if the person typing to me just stopped briefly OR did they clear their message entirely. That is where `onUserClearedTyping` or something similar would fit in. That way I as the developer could setup `onUserStoppedTyping` to be more of a pause in the action and would still display a typing indicator of sorts but in a manner that shows the other person is merely pausing and hasn't yet sent/deleted the full text and `onUserClearedTyping` would be a way to completely remove any indication that the user was typing at all because they've cleared their chat input box entirely.

I believe Skype has functionality similar to what I'm describing (or at least used to) where active typing (`onUserStartedTyping`) was a moving pen icon and the paused but not deleted (`onUserStoppedTyping`) the pen would lie down on the screen and my proposed `onUserClearedTyping` came in where the user deleted the message and the pen went away entirely.

Just a thought for the future. This isn't blocking future dev I'm working on but would be one of those nice to haves.

**Comment by callum-oakley** [comment]
I like it! Thanks for the detailed description -- will bring it up with the rest of the team. :slightly_smiling_face:

**Comment by callum-oakley** [comment]
Closing this as stale (and because it's not a feature request for the SDK, more a feature request for the product as a whole).
