### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by gianpaj** [pusher/chatkit-client-js#68]
🙏

**Comment by eveevans** [comment]
What "Flow Types" means ?

**Comment by gianpaj** [comment]
flow type definitions. similar to [typescript type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped)
https://flow.org/en/docs/types/

**Comment by gianpaj** [comment]
If this done the IDE, like Visual Studio Code, will automatically hint function signatures, etc.

For example:
```js
import type { PusherUser } from '@pusher/chatkit';
```

<img width="616" alt="actioncreator_js_ _mobileapp" src="https://user-images.githubusercontent.com/899175/41654320-bfb3ece6-7491-11e8-914f-87628cd1523a.png">

**Comment by callum-oakley** [comment]
Closing as stale. This is in our internal backlog but is unlikely to be scheduled any time soon. Contact support if this is a feature that matters a lot to you!
