### ISSUE TITLE
Types seem to be missing

### ISSUE THREAD

**Issue by gildebrand** [pusher/chatkit-client-js#69]
I'm using chatkit-client-js together with Angular 5 and TypeScript. It seems like the type hints, which worked in 0.7.5, has stopped working in 0.7.9. Now my IDE (WebStorm) gives me read warnings everywhere. I guess that creating a `@types` package for the types would be a viable solution, but I think it would be even better if the type hints was included in the package to begin with!

**Comment by callum-oakley** [comment]
I'm surprised the hints worked in 0.7.5 since the SDK hasn't had types since 0.6.X! Regardless, we should definitely provide type definitions, watch this space :)

**Comment by gildebrand** [comment]
Hey! Is this something that is likely to make it into the upcoming versions? 😄

**Comment by teminer** [comment]
@gildebrand yes! But not sure exactly when yet, as I mentioned in the other issue we need to focus on improving reliability and scalability first.

**Comment by seanghay** [comment]
Most pusher repos are written with TypeScript, however, this one is in ES6. Why did you choose to do that?

**Comment by williamluke4** [comment]
Any movement on this?

**Comment by paulokuda** [comment]
Big +1 on adding types 🙏

**Comment by Alex-231** [comment]
@callum-oakley I'd like to write some types for this project. Should I fork master or the v5 branch?

**Comment by callum-oakley** [comment]
This has been put on our internal backlog. Please [contact support](mailto:support@pusher.com) if this is particularly important for you!
