### ISSUE TITLE
Allow to send a message with an attachment without requiring a text field

### ISSUE THREAD

**Issue by gianpaj** [pusher/chatkit-client-js#83]
Currently the `sendMessage()` function and API requires to send a `text` field.
It can't be an empty string or null.

https://docs.pusher.com/chatkit/reference/javascript#attachment

```js
info: {
  error: "services/chatkit/unprocessable_entity/validation_failed",
  error_description: "Field `text` is empty",
  error_uri: "https://docs.pusher.com/errors/services/chatkit/unprocessable_entity/validation_failed"
}
```

<img src="https://user-images.githubusercontent.com/899175/41509980-66fbf856-7265-11e8-8f06-a7ed985eb862.png" width="300"/>

Notice the empty space between the image and timestamp.

This causes an image to show like this by default on [react-native-gifted-chat](https://github.com/FaridSafi/react-native-gifted-chat).

Sometimes you just want to send an image without a caption or text. I think it's a common use case in WhatApp, Facebook Messenger and other chat applications.

**Comment by hamchapman** [comment]
Hey @gianpaj sorry for the delay in getting back to you. This is something we've got planned for the future. It's currently not high priority because of the ability to send a message with an empty string as the text, but it is something we'll make possible in the future 👍

**Comment by gianpaj** [comment]
@hamchapman no worries.
FYI, the chatkit-client-js requires at least a single character. it won't work with an empty string.

**Comment by mdpye** [comment]
Hi. This will be possible soon, when we bring out multi-part messages. Once this is live, each message can have multiple parts, and any or all of them can be attachments.

Watch this space.

**Comment by schmijos** [comment]
This is possible now, right? See the lower part of <https://pusher.com/docs/chatkit/reference/javascript#sending-a-message>

**Comment by callum-oakley** [comment]
This is supported in the latest version of the API.
