### ISSUE TITLE
Attachment token expired

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#86]
Good day guys! Looks like amazon use very short live links.
`<Code>AccessDenied</Code>`
`<Message>Request has expired</Message>`
`<X-Amz-Expires>60</X-Amz-Expires>`

Should I fetchAttachment on every click event on the link? Its right workflow?

**Comment by hamchapman** [comment]
Hey @alexey13 - the workflow we imagined is that you'd call `fetchAttachment` and use the link returned to immediately render an image / video / audio etc. If you want to use the attachment later on then yep, just call `fetchAttachment` again when your user wants to interact with the attachment 👍

**Comment by alexey13** [comment]
Ok, thanks!
