### ISSUE TITLE
access_token Authorisation issue (provide an example for access_token usage?)

### ISSUE THREAD

**Issue by swhiber** [pusher/chatkit-client-js#91]
I've been trying to add a new room via a request to my server
```javascript
fetch('http://localhost:3001/newRoom', {
                    method: 'POST',
                    headers: { 
                        'Content-Type': 'application/json',
                        'Authorization': 'Bearer '+btoa(this.state.accessToken)
                    },
                    body: JSON.stringify({
                            creatorId: (this.state.origin_username).toString(),
                            name: `${this.state.origin_username}&${this.state.dest_username}`,
                            userIds: [currentUser.id,this.state.dest_username]
                    }) 
                })
                .then((response) => {
                    console.log(response.json());
                })
                .catch(error => console.error('error', error))
```

However I receive this error
`error: 'services/chatkit_authorizer/authorization/invalid_token_subject',
  error_description: 'Missing token subject',
  error_uri: 'https://docs.pusher.com/errors/services/chatkit_authorizer/authorization/invalid_token_subject' `

I'm unsure if I'm making a silly error or whether there is an issue with SDK. Some more documentation on the topic would probably resolve this either way :)

**Comment by gianpaj** [comment]
Looks like your Auth Pusher server is not returning the correct data to your ChatKit client.

Using express 4.x you can this in your Node.Js server:
```js
   const auth = chatkit.authenticate({
      userId: user_id, // your app user id
      authPayload: req.body,
    });
    return res.json(auth.body);
```

See also this example:
https://github.com/pusher/chatkit-server-node/blob/master/examples/auth_server.js

**Comment by hamchapman** [comment]
A missing subject means that there's no `sub` claim in the token that is being generated. We use the `sub` (subject) claim to store the user's ID, so it sounds like you're not providing a user ID when you generate your token(s).

**Comment by swhiber** [comment]
It was to do with the
