### ISSUE TITLE
Room-level presence 

### ISSUE THREAD

**Issue by nbransby** [pusher/chatkit-client-js#93]
My use case requires me to show user presence at a room level, with a user considered online in a room if they have an active room subscription.

**Comment by callum-oakley** [comment]
Hmmm, I'm afraid this is not currently supported, but consider this a feature request!

**Comment by neuropass** [comment]
This makes sense and I believe should be a must have. @nbransby could you explain how you did it with channels please? I would like to replicate it.

**Comment by neuropass** [comment]
any news here please? right now its still not possible to know when a user is online on X room only.
although pusher site says it is: https://github.com/pusher/chatkit-client-js/issues/169 I see no docs on how to achieve this.  unless I'm missing the obvious. Please advice

**Comment by callum-oakley** [comment]
Closing this because it's a feature request for the product as a whole not for this SDK. Please [contact support](mailto:support@pusher.com) if this is important for your use case.
