### ISSUE TITLE
update current user properties

### ISSUE THREAD

**Issue by nbransby** [pusher/chatkit-client-js#94]
I need to set the customData of the current user but there does not seem to be a function for this (I also need this in the android client but posting here because this project seems more active)

Once the customData is updated would other connected users be notified? I would need this too.

**Comment by callum-oakley** [comment]
Hi @nbransby 

We've got some work planned to improve the whole custom data flow (including informing other connected clients of updates), at which point we'll certainly add these methods to the client SDKs.

At the moment though your best bet is probably to proxy updates through the server and [use the API directly](https://docs.pusher.com/chatkit/reference/api#updating-a-user). Unfortunately other clients won't get real time updates though, which is partly why we haven't added these methods to the clients yet!

**Comment by nbransby** [comment]
Thanks for the update @callum-oakley ! Sounds great, I did read about the custom data improvements - must be nearly finished now GDPR is a distant memory? :)

**Comment by callum-oakley** [comment]
We've been working hard on scaling since GDPR, but it's fairly high on our backlog so watch this space :)

**Comment by callum-oakley** [comment]
Closing this because it's a feature request for the product as a whole not for this SDK. It's in our internal backlog but not currently prioritised. If this is important to your use case please [contact support](mailto:support@pusher.com).
