### ISSUE TITLE
Having trouble getting currentUser

### ISSUE THREAD

**Issue by Gabriel416** [pusher/chatkit-client-js#96]
I'm trying to set up chatkit for my app and everything seems to work until I try to connect and get the currentUser.  Looks like one request from the server results in a 204 and the other request seems fine. The function below is fired once on mount of a component.

```javascript
connect({ commit, state, rootState }) {
      let chatManager = new Chatkit.ChatManager({
        instanceLocator: 'v1:us1:56256341-7b34-4ec2-a238-be971f1ab0d0',
        userId: rootState.user.account.id.toString(),
        tokenProvider: new Chatkit.TokenProvider({
          url: 'http://localhost:3333/api/v1/token',
          headers: {
            Authorization: 'bearer ' + rootState.authentication.token,
          },
        }),
      });
      console.log(chatManager, 'chat manager');
      chatManager
        .connect()
        .then(currentUser => {
          console.log(currentUser, 'CURRENT USER');
        })
        .catch(error => console.error('error', error));
    },
```

![screenshot 4](https://user-images.githubusercontent.com/23641060/44634193-556f9580-a964-11e8-85b3-7b65b318c277.png)

![screenshot 6](https://user-images.githubusercontent.com/23641060/44634204-7fc15300-a964-11e8-9016-ffa707925357.png)

![screenshot 5](https://user-images.githubusercontent.com/23641060/44634195-599bb300-a964-11e8-9dd7-7a4ba89d4199.png)

**Comment by Gabriel416** [comment]
![screenshot 8](https://user-images.githubusercontent.com/23641060/44634292-db401080-a965-11e8-9ec2-31b1ee43b041.png)

Looks like the user was created in the pusher dashboard. But I can't seem to connect.  Please let me know if I'm missing anything silly, or if more info is needed. Thanks.

**Comment by kkcodes** [comment]
Hi Gabriel416,

For the second last image, where you can see the Ajax response which has the status, body, and header. So, instead of sending those entire details, return the body only and set the status code as whatever you get. 

Also, hope that the  `rootState.authentication.token`, generates the correct JWT.

**Comment by Gabriel416** [comment]
Hello @kkcodes ! server side I'm sending the body now and I'm running into this

![screenshot 10](https://user-images.githubusercontent.com/23641060/44692325-6a195f80-aa30-11e8-8c2c-2565240171f6.png)


This is what I'm getting back from my server

![screenshot 9](https://user-images.githubusercontent.com/23641060/44692331-756c8b00-aa30-11e8-85bc-46a0bbf8918b.png)

`rootState.authentication.token` is an api token needed to make requests to my server and I have verified it is correct.

**Comment by callum-oakley** [comment]
Hi @Gabriel416,

The error is complaining that there is no user ID in your token, which the connection request needs to identify who the user is. Can I see the code you're using to generate the token?

**Comment by Gabriel416** [comment]
![screenshot 11](https://user-images.githubusercontent.com/23641060/44756588-52f27480-aaf9-11e8-8f36-c96cbe961f1c.png)

The register method is where I'm creating the chatkit user.

![screenshot 12](https://user-images.githubusercontent.com/23641060/44756609-68679e80-aaf9-11e8-91c5-a49f2879e98d.png)

this method is the one that gets hit for the tokenProvider

![screenshot 13](https://user-images.githubusercontent.com/23641060/44756645-7e755f00-aaf9-11e8-8bcc-693fecf5640d.png)

this is what my ChatkitService looks like

**Comment by callum-oakley** [comment]
What version of the node SDK are you using? In the latest version at least, `authenciate` takes a single object with a `userId`. e.g.

```javascript
app.post('/auth', (req, res) => {
  const authData = chatkit.authenticate({
    userId: req.query.user_id
  });

  res.status(authData.status)
     .send(authData.body);
})
```

**Comment by Gabriel416** [comment]
@callum-oakley  thank you works like a charm now! I'm using `"@pusher/chatkit-server": "^0.12.2"`. I was loosely following https://pusher.com/tutorials/chat-adonisjs#get-user-details and it seems like there is some outdated stuff. Thanks again cheers.

**Comment by callum-oakley** [comment]
Great to hear! Thanks for letting us know :)
