### ISSUE TITLE
Event Handler for Chat Disconnect

### ISSUE THREAD

**Issue by kkcodes** [pusher/chatkit-client-js#98]
Hi,

We can have an event handler, or a method, in order to handle the scenario, when the chat disconnects, since at this point of time, there is no way to show anything in the UI, and with that even if the user sends the message, there  is no way to re-send the message again, like other Messaging providers.

We can include this as a feature request.

Thanks!

**Comment by neuropass** [comment]
ah yes indeed a great idea. We should have a method/function to do this.

**Comment by anchetaWern** [comment]
any update on this? basically just a simple way of knowing when Chatkit needs to be re-initialized again after the app is idle for a long time and it got offset by the OS.

**Comment by callum-oakley** [comment]
This feature request is on our internal backlog. Please [contact support](support@pusher.com) with more details if it's particularly important to your use case.
